import json
import os
import sys
import ollama

class LocalAnalyzer:
    def __init__(self, model="gemini-3-pro-preview"):
        self.model = model
        self.raw_data_dir = "raw_data"

    def load_parsed_data(self, date_str):
        """Loads the clean JSON data created by the Parser."""
        filename = f"parsed_debates_{date_str}.json"
        if not os.path.exists(filename):
            print(f"Error: {filename} not found. Did you run parser.py?")
            return None
        
        with open(filename, 'r', encoding='utf-8') as f:
            return json.load(f)

    def generate_executive_summary(self, all_topics, date_str):
        """
        Reads the titles and activity levels of all topics to write a Lead Story.
        """
        print("  > Generating Executive Summary (Lead Story)...")
        
        # 1. Create a "Day at a Glance" list for the AI
        agenda_summary = ""
        for topic in all_topics:
            title = topic.get('topic', 'Unknown')
            speaker_count = len(topic.get('speeches', []))
            agenda_summary += f"- {title} ({speaker_count} speakers)\n"

        # 2. Prompt for the Intro
        prompt = f"""
        You are the Chief Political Editor for a major Irish newspaper. 
        Write a 'Lead Story' introduction (approx 200-300 words) for today's Dáil sitting.

        DATE: {date_str}

        Here is the agenda and the level of activity (number of speakers) for each topic:
        {agenda_summary}

        **INSTRUCTIONS:**
        1. Identify the most heavily debated topics (highest speaker counts) and frame the intro around them.
        2. Set the scene: "The Dáil met today to discuss..."
        3. Be journalistic and formal. This is the "Hook" for the reader. Avoid the overuse of adjectives.
        4. Focus on the main themes.
        """

        try:
            response = ollama.chat(model=self.model, messages=[
                {'role': 'user', 'content': prompt},
            ])
            return response['message']['content']
        except Exception as e:
            print(f"  Error generating summary: {e}")
            return "### Daily Overview\n*Summary generation failed.*"

    def analyze_topic(self, topic_data):
        """
        Sends a single topic to the LLM for a detailed, narrative blog section.
        """
        topic_title = topic_data.get('topic', 'Unknown Topic')
        speeches = topic_data.get('speeches', [])

        if not speeches:
            return None

        # Prepare text (truncated to avoid crashing local hardware)
        full_text = ""
        for s in speeches:
            full_text += f"{s['speaker']}: {s['text']}\n"
        
        print(f"  > Analyzing '{topic_title[:30]}...' ({len(speeches)} speeches)")

        if len(full_text) > 40000:
            full_text = full_text[:40000] + "\n...[text truncated]..."

        # Narrative Prompt
        prompt = f"""
        You are a senior political correspondent reporting on the Irish Dáil. 
        Write a detailed narrative news report based on the transcript below.

        TOPIC: {topic_title}

        **STRICT GUIDELINES:**
        1. **NO BULLET POINTS:** Write in full, flowing paragraphs only.
        2. **NARRATIVE FLOW:** Describe the debate dynamically ("The Minister argued...", "However, Deputy X countered with...").
        3. **DIRECT QUOTES:** Use quotes from the text to capture the mood.
        4. **STRUCTURE:** Start with the issue, describe the key arguments, and end with the outcome.
        5. **LENGTH:** Be comprehensive.

        TRANSCRIPT:
        {full_text}
        """

        try:
            response = ollama.chat(model=self.model, messages=[
                {'role': 'user', 'content': prompt},
            ])
            return response['message']['content']
        except Exception as e:
            print(f"  Error querying Ollama: {e}")
            return f"\n### {topic_title}\n*Error analyzing this section.*\n"

    def run(self, date_str):
        data = self.load_parsed_data(date_str)
        if not data:
            return

        blog_filename = f"blog_post_{date_str}.md"
        
        print(f"Starting analysis for {date_str} using {self.model}...")
        print(f"Output will be streamed to: {blog_filename}")

        # --- STEP 1: Generate the Lead Story ---
        executive_summary = self.generate_executive_summary(data, date_str)

        # Write Header and Lead Story
        with open(blog_filename, "w", encoding="utf-8") as f:
            f.write(f"# Dáil Debate Report: {date_str}\n")
            f.write(f"*Generated by {self.model}*\n\n")
            f.write("## Executive Summary\n")
            f.write(executive_summary)
            f.write("\n\n---\n")

        # --- STEP 2: Process Individual Topics ---
        for section in data:
            # Skip empty sections
            if not section.get('speeches'):
                continue

            analysis = self.analyze_topic(section)
            
            if analysis:
                # Append to file
                with open(blog_filename, "a", encoding="utf-8") as f:
                    f.write("\n" + analysis + "\n\n---\n")

        print(f"\nSUCCESS! Blog post generated: {blog_filename}")

if __name__ == "__main__":
    target_date = None
    if len(sys.argv) > 1:
        target_date = sys.argv[1]
    else:
        try:
            files = [f for f in os.listdir(".") if f.startswith("parsed_debates_")]
            files.sort(reverse=True)
            if files:
                target_date = files[0].replace("parsed_debates_", "").replace(".json", "")
            else:
                print("No parsed data found. Run parser.py first.")
                sys.exit(1)
        except Exception:
            pass

    if target_date:
        analyzer = LocalAnalyzer(model="gemini-3-pro-preview")
        analyzer.run(target_date)
    else:
        print("Could not determine date. Usage: python analyzer.py YYYY-MM-DD")
